<!DOCTYPE html>
<html>

<head>
    <title>This Email generated by www.codechief.org</title>
</head>

<body>

  @php
      $totalPrice =0;
      $bookCount =0;
  @endphp

    <h3>Beste {{ $order->firstname }}</h3>

    <p>
        Bedankt voor je bestelling met ordernummer {{ $order->id }}. Uw bestelling wordt zo spoedig mogelijk verzonden. De boeken hebben een levertijd van 2 á 3 werkdagen. Heeft u een product besteld uit het Kratmeister-assortiment, houd dan rekening met een levertermijn van 5 werkdagen.
    </p>


    <h4>Bezorgadres</h4>
    <div>{{ $order->firstname }} {{ $order->lastname }} </div>
    <div>{{ $order->streetname }} {{ $order->housenumber }} </div>
    <div>{{ $order->postcode }} , {{ $order->city }}</div>

    <h4>Overzicht bestelling</h4>


    @isset($order->kratmeister_orders)

        <table style="width: 100%">
            <tr>
                <th style="text-align: left">Categorie</th>
                <th style="text-align: left">Product ID</th>
                <th style="text-align: left">Titel</th>
                {{-- <th style="text-align: left">Bier merk</th>
                <th style="text-align: left">Verpakkings grote</th> --}}
                <th style="text-align: left">Prijs</th>

            </tr>

            @foreach (json_decode($order->kratmeister_orders, true) as $kratmeister_order)
                <tr>
                    <td>Kratmeister</td>

                    <td> {{ $kratmeister_order['kratmeister_id'] }}</td>

                    <td> {{ $kratmeister_order['kratmeister_sticker_title'] }}</td>
                    {{-- <td> {{ $kratmeister_order['kratmeister_beer_brand'] }}</td>
                    @switch($kratmeister_order['packageSize'])
                        @case('single_can_price')
                            <td>1 Blikje</td>

                        @break
                        @case('single_small_bottle_price')
                            <td>1 Flesje</td>
                        @break

                        @case('single_large_bottle_price')
                            <td>0.75l fles</td>
                        @break
                        @case('sixpack_bottle_price')
                            <td>sixpack flesjes</td>
                        @break
                        @case('beercase_price')
                            <td>1 krat</td>
                        @break
                        @case('single_large_bottle_price')
                            <td>0.75l fles</td>
                        @break
                        @default

                    @endswitch --}}

                    @php
                      $totalPrice = $totalPrice+($kratmeister_order['kratmeister_beer_price']+$kratmeister_order['kratmeister_sticker_price']);

                    @endphp

                    <td> €@convert($kratmeister_order['kratmeister_beer_price']+$kratmeister_order['kratmeister_sticker_price'])
                    </td>

                  </tr>


        @endforeach
      </table>

    @endisset

    <br>

    @isset($order->book_orders)

        <table style="width: 100%">
            <tr>
                <th style="text-align: left">Categorie</th>
                <th style="text-align: left">Product ID</th>
                <th style="text-align: left">Titel</th>
                <th style="text-align: left">Aantal</th>
                <th style="text-align: left">Prijs</th>

            </tr>



            @foreach (json_decode($order->book_orders, true) as $book_order)
                <tr>
                    <td>Boek</td>

                    <td> {{ $book_order['book_id'] }}</td>

                    <td> {{ $book_order['book_title'] }}</td>
                    <td> {{ $book_order['book_count'] }}</td>

                    @php
                        $bookCount =$bookCount+$book_order['book_count'];
                        $totalPrice = $totalPrice+ ($book_order['book_count'] *$book_order['book_price']);
                    @endphp

                    <td> €@convert($book_order['book_count'] *$book_order['book_price'])</td>

                  </tr>


        @endforeach
      </table>

    @endisset
    <br>

    <div><span style="font-weight: bold;">Boekkorting</span>
      <span>

   @if ($bookCount > 1)


   €@convert(5)

   @php
       $totalPrice =$totalPrice- 5
   @endphp
   @else
   €@convert(0)

   @endif

    </span></div>

    <div><span style="font-weight: bold;">Verzendkosten</span> <span>Gratis</span></div>
    <div><span style="font-weight: bold;">Totaal</span> <span>€@convert($totalPrice)</span></div>
    <div><span style="font-weight: bold;">Betaald met iDeal</span> <span>€@convert($totalPrice)</span></div>
    <div><span style="font-weight: bold;">Nog the voldoen</span> <span>€@convert(0)</span></div>


    <h4>Bestelling wijzigen</h4>
    <p>Wil je jouw bestelling wijzigen of retourneren? Neem dan zo snel mogelijk contact met ons op. Mail naar info@thewildeast.nl.</p>


{{-- Totaal € 579,55
Betaald met iDEAL € 579,55
Nog te voldoen € 0,00 --}}


    {{-- <hr class="mt-10 mb-10" />

            <div class="row">
                <div class="col-md-6">

                    <dl class="row">

                        <dt class="col-sm-4">Kratmeister template</dt>
                        <dd class="col-sm-8">{{ $kratmeister_order['kratmeister_sticker_title'] }}</dd>

                        <dt class="col-sm-4">Database ID</dt>
                        <dd class="col-sm-8">{{ $kratmeister_order['kratmeister_id'] }}</dd>

                        <dt class="col-sm-4">Naam Label</dt>
                        <dd class="col-sm-8">{{ $kratmeister_order['name_user'] }}</dd>

                        <dt class="col-sm-4">Bier merkt</dt>
                        <dd class="col-sm-8">{{ $kratmeister_order['kratmeister_beer_brand'] }}</dd>

                        <dt class="col-sm-4">Verpakking size</dt>

                        @switch($kratmeister_order['packageSize'])
                            @case('single_can_price')
                                <dd class="col-sm-8">1 Blikje</dd>

                            @break
                            @case('single_small_bottle_price')
                                <dd class="col-sm-8">1 Flesje</dd>
                            @break

                            @case('single_large_bottle_price')
                                <dd class="col-sm-8">0.75l fles</dd>
                            @break
                            @case('sixpack_bottle_price')
                                <dd class="col-sm-8">sixpack flesjes</dd>
                            @break
                            @case('beercase_price')
                                <dd class="col-sm-8">1 krat</dd>
                            @break
                            @case('single_large_bottle_price')
                                <dd class="col-sm-8">0.75l fles</dd>
                            @break
                            @default

                        @endswitch

                        <dt class="col-sm-4">Download photo</dt>
                        <dd class="col-sm-8">

                            <a class="btn btn-success"
                                href="{{ route('getfile', ['filename' => $kratmeister_order['user_photo_path'], 'username' => $kratmeister_order['name_user']]) }}">Download
                                foto</a>


                        </dd>



                    </dl>


                </div>

                <div class="col-md-6">

                    {{ $kratmeister_order['back_label_text'] }}


                </div>
            </div>

        @endforeach --}}




</body>

</html>
